#!/bin/sh

poudriere jail -c -j 132-opnsense -v 13.2-RELEASE -a amd64

poudriere ports -c -m git+https -U https://github.com/opnsense/ports.git -B master -p opnsense
poudriere ports -c -m git+https -U https://github.com/crowdsecurity/packaging-freebsd.git -B main -p freebsd_crowdsec

cat <<EOT >/root/port_opnsense
security/crowdsec
security/crowdsec-firewall-bouncer
security/crowdsec-blocklist-mirror
EOT

exit 0

poudriere bulk -J 4 -j 132-opnsense -p opnsense -O freebsd_crowdsec -f /root/port_opnsense
