#!/bin/sh

set -eu

pkg install -y python poudriere-devel git

mkdir -p /usr/local/etc/ssl/certs
mkdir -p /usr/local/etc/ssl/keys
chmod 0600 /usr/local/etc/ssl/keys

if test ! -f "/usr/local/etc/ssl/keys/poudriere.key"; then
    openssl genrsa -out /usr/local/etc/ssl/keys/poudriere.key 4096
    chmod 0600 /usr/local/etc/ssl/keys/poudriere.key
fi

if test ! -f "/usr/local/etc/ssl/certs/poudriere.certs.key"; then
    openssl rsa -in /usr/local/etc/ssl/keys/poudriere.key -pubout -out /usr/local/etc/ssl/certs/poudriere.certs
fi

mkdir -p /usr/ports/distfiles

# https://download.freebsd.org/snapshots/amd64/amd64/
# https://www.freebsd.org/releases/14.0R/schedule/
# https://download.freebsd.org/releases/amd64/amd64/
#poudriere jail -c -j 124 -v 12.4-RELEASE -a amd64
