#!/bin/sh

# poudriere jail -c -j 124 -v 12.4-RELEASE -a amd64
poudriere jail -c -j 132 -v 13.2-RELEASE -a amd64
poudriere jail -c -j 140 -v 14.0-BETA2 -a amd64
poudriere jail -c -j 150 -v 15.0-CURRENT -a amd64

poudriere ports -c -m git+https -U https://git.freebsd.org/ports.git -B main -p freebsd
poudriere ports -c -m git+https -U https://github.com/crowdsecurity/packaging-freebsd.git -B main -p freebsd_crowdsec

cat <<EOT >/root/port_freebsd
security/crowdsec
security/crowdsec-firewall-bouncer
security/crowdsec-blocklist-mirror
EOT

exit 0

# poudriere bulk -J 4 -j 124 -p freebsd -O freebsd_crowdsec -f /root/port_freebsd
poudriere bulk -J 4 -j 132 -p freebsd -O freebsd_crowdsec -f /root/port_freebsd
poudriere bulk -J 4 -j 140 -p freebsd -O freebsd_crowdsec -f /root/port_freebsd
poudriere bulk -J 4 -j 150 -p freebsd -O freebsd_crowdsec -f /root/port_freebsd
