#!/bin/sh

set -eu

pkg install -y python poudriere-devel git

mkdir -p /usr/local/etc/ssl/certs
mkdir -p /usr/local/etc/ssl/keys
chmod 0600 /usr/local/etc/ssl/keys

if test ! -f "/usr/local/etc/ssl/keys/poudriere.key"; then
    openssl genrsa -out /usr/local/etc/ssl/keys/poudriere.key 4096
    chmod 0600 /usr/local/etc/ssl/keys/poudriere.key
fi

if test ! -f "/usr/local/etc/ssl/certs/poudriere.certs.key"; then
    openssl rsa -in /usr/local/etc/ssl/keys/poudriere.key -pubout -out /usr/local/etc/ssl/certs/poudriere.certs
fi

mkdir -p /usr/ports/distfiles

poudriere jail -c -j 140 -v 14.0-CURRENT -a amd64
poudriere jail -c -j 132 -v 13.2-STABLE -a amd64

poudriere ports -c -m git+https -U https://git.freebsd.org/ports.git -B main -p freebsd
poudriere ports -c -m git+https -U https://github.com/crowdsecurity/packaging-freebsd.git -B main -p freebsd_crowdsec

poudriere ports -c -m git+https -U https://github.com/pfsense/FreeBSD-ports.git -B devel -p pfsense
poudriere ports -c -m git+https -U https://github.com/crowdsecurity/pfSense-pkg-crowdsec.git -B main -p pfsense_crowdsec

# FreeBSD

cat <<EOT >/root/port_freebsd
security/crowdsec
security/crowdsec-firewall-bouncer
security/crowdsec-blocklist-mirror
EOT

# pfSense

cat <<EOT >/root/port_pfsense
security/crowdsec
security/crowdsec-firewall-bouncer
security/crowdsec-blocklist-mirror
security/pfSense-pkg-crowdsec
EOT

# poudriere bulk -J 1 -j 132 -p freebsd -O freebsd_crowdsec -f /root/port_freebsd
# poudriere bulk -J 1 -j 140 -p freebsd -O freebsd_crowdsec -f /root/port_freebsd

# poudriere bulk -J 1 -j 140 -p pfsense -O freebsd_crowdsec -O pfsense_crowdsec -f /root/port_pfsense
